#!/bin/bash

set -e

if [ $# -lt 2 ]
then
    echo "Error: harness requires two arguments" >&2
    echo "- Grace command" >&2
    echo "- Directory of tests to run" >&2
    exit 1
fi
GRACE="$1"
TESTDIR="$2"
shift
shift
cd "$TESTDIR"

TYPE="normal"

if [ $# -gt 0 ]
then
    tests=( "$@" )
else
    tests=( *_test.grace )
fi

set +e

pass() {
    echo "!PASS" >> test-$$.log
}
fail() {
    echo "!FAIL $*" >> test-$$.log
}

NUM_TESTS=0
NUM_PASS=0
NUM_UNEXPECTED_SUCCESS=0
NUM_WRONG_OUTPUT=0
NUM_RUNTIME_FAILURE=0
NUM_COMPILE_ERROR=0
echo "Beginning test run at $(date)" > test.log
for tcase in "${tests[@]}"
do
    if ! [ -e "$tcase" ]
    then
        tcase=$(echo $tcase*_test.grace)
    fi
    echo ================================================== >> test-$$.log
    echo Beginning case "$tcase"... >>test-$$.log
    NUM_TESTS=$((NUM_TESTS + 1))
    if [ "${tcase%fail_test.grace}" = "$tcase" ]
    then
        COMMAND="$GRACE --no-run $tcase"
        if eval "$COMMAND" > test-$$.log 2>&1
        then
            COMMAND="$GRACE $tcase"
            if ! eval "$COMMAND" > test-$$.out 2>&1
            then
                NUM_RUNTIME_FAILURE=$((NUM_RUNTIME_FAILURE + 1))
                printf "%3i ERROR: %-40s produced runtime error\n" "${NUM_TESTS}" "$tcase"
                fail "runtime failure"
            elif diff test-$$.out ${tcase%_test.grace}.out
            then
                NUM_PASS=$((NUM_PASS + 1))
                printf "%3i PASS:  %s\n" "${NUM_TESTS}" "$tcase"
                pass
                rm -f test-$$.out
            else
                NUM_WRONG_OUTPUT=$((NUM_WRONG_OUTPUT + 1))
                printf "%3i ERROR: %-40s produced wrong output\n" "${NUM_TESTS}" "$tcase"
                fail "wrong output"
            fi
        else
            NUM_COMPILE_ERROR=$((NUM_COMPILE_ERROR + 1))
            printf "%3i ERROR: %-40s failed statically\n" "${NUM_TESTS}" "$tcase"
            fail "compile error"
        fi
    else
        NUM_TESTS=$((NUM_TESTS - 1))
        if false
        then
        COMMAND="$GRACE --make --native $tcase"
        if eval "$COMMAND" > test-$$.log 2>&1
        then
            printf "%3i ERROR: %-40s should have failed to compile\n" "${NUM_TESTS}" "$tcase"
            NUM_UNEXPECTED_SUCCESS=$((NUM_UNEXPECTED_SUCCESS + 1))
            fail "compiled"
        else
            NUM_PASS=$((NUM_PASS + 1))
            printf "%3i %s: %s\n" "${NUM_TESTS}" "PASS" "$tcase"
            pass
        fi
        fi
    fi
    cat test-$$.log >> test.log
    if [ -e test-$$.out ]
    then
        echo "Got output:" >> test.log
        cat test-$$.out >> test.log
        echo "Expected output:" >> test.log
        cat ${tcase%_test.grace}.out >> test.log
    fi
    rm -f test-$$.log test-$$.out ${tcase%%.*} *.bc *.ll *.gco *.s *.gcn *.c *.java *.class *.gct
done

echo Ran $NUM_TESTS tests.
echo $NUM_PASS/$NUM_TESTS passed.
echo "$NUM_UNEXPECTED_SUCCESS tests compiled that shouldn't have."
echo "$NUM_RUNTIME_FAILURE tests compiled but failed at runtime."
echo "$NUM_WRONG_OUTPUT tests ran without error but produced the wrong output."
echo "$NUM_COMPILE_ERROR tests did not compile but should have."
NUM_FAIL=$((NUM_TESTS - NUM_PASS))
if [ $NUM_FAIL -gt 0 ]
then
    exit 1
fi
